package com.example.order_service.exception;

public enum ErrorCode {
    ORDER_NOT_FOUND,
    PRODUCT_NOT_FOUND,
    INVENTORY_RESERVATION_NOT_FOUND,
    ORDER_UPDATE_NOT_ALLOWED,
    ORDER_DELETE_NOT_ALLOWED,
    AUTH_INVALID_CREDENTIALS,
    AUTH_EMAIL_ALREADY_EXISTS,
    AUTH_USER_DISABLED,
    AUTH_DEFAULT_ROLE_NOT_FOUND,
    RATE_LIMIT_EXCEEDED,
    VALIDATION_FAILED,
    MALFORMED_REQUEST,
    ENDPOINT_NOT_FOUND,
    INTERNAL_SERVER_ERROR
}
